image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew  # права на запуск скрипта gradlew на люникс

build_script:
#  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
  - ./gradlew test --info -Dselenide.headless=true